=== nikolastosevski/proba/prvenstvo.dtd
<!ELEMENT RasporedTakmicenja (Utakmica)+>

<!ELEMENT Utakmica (Tim1, Tim2, Termin)>

<!ELEMENT Tim1 ((Igrac)+, Trener, Kontinent, Zemlja, (Medalje)*)>
<!ELEMENT Tim2 ((Igrac)+, Trener, Kontinent, Zemlja, (Medalje)*)>

<!ELEMENT Igrac (Ime, Prezime, Klub, BrojUtakmica)>

<!ELEMENT Ime (#PCDATA)>
<!ELEMENT Prezime (#PCDATA)>
<!ELEMENT Klub (#PCDATA)>
<!ELEMENT BrojUtakmica (#PCDATA)>

<!ELEMENT Trener (Ime, Prezime, Godine)>
<!ELEMENT Godine (#PCDATA)>

<!ELEMENT Kontinent (#PCDATA)>
<!ELEMENT Zemlja (#PCDATA)>

<!ELEMENT Medalje (Mesto, Medalja, Godina)>

<!ELEMENT Mesto (Lokacija)>

<!ELEMENT Lokacija (Region, Grad)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT Grad (#PCDATA)>
<!ATTLIST Lokacija stadion CDATA #REQUIRED>
<!ATTLIST Lokacija brMesta CDATA #IMPLIED>

<!ELEMENT Medalja (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>

<!ELEMENT Termin (Datum, Cas)>
<!ELEMENT Datum (#PCDATA)>
<!ELEMENT Cas (#PCDATA)>
<!ATTLIST Termin tvPrenos CDATA #REQUIRED>
<!ATTLIST Termin kanal CDATA #IMPLIED>

=== nikolastosevski/proba/SvetskoPrvenstvo.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE RasporedTakmicenja SYSTEM "prvenstvo.dtd">
<RasporedTakmicenja xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com prvenstvo.xsd">
  <Utakmica>
    
    <Tim1>
      <Igrac>
        <Ime>Ime1</Ime>
        <Prezime>Prezime1</Prezime>
        <Klub>Klub1</Klub>
        <BrojUtakmica>1</BrojUtakmica>
      </Igrac>
      <Trener>
        <Ime>Trener1</Ime>
        <Prezime>PTrener1</Prezime>
        <Godine>37</Godine>
      </Trener>
      <Kontinent>Azija</Kontinent>
      <Zemlja>Kina</Zemlja>
      <Medalje>
        <Mesto>
          <Lokacija stadion="Stadion1" brMesta="25000">
            <Region>Region1</Region>
            <Grad>Grad1</Grad>
          </Lokacija>
        </Mesto>
        <Medalja>Zlato</Medalja>
        <Godina>2019</Godina>
      </Medalje>
    </Tim1>

    <Tim2>
      <Igrac>
        <Ime>Ime2</Ime>
        <Prezime>Prezime2</Prezime>
        <Klub>Klub2</Klub>
        <BrojUtakmica>2</BrojUtakmica>
      </Igrac>
      <Trener>
        <Ime>Trener2</Ime>
        <Prezime>PTrener2</Prezime>
        <Godine>53</Godine>
      </Trener>
      <Kontinent>Evropa</Kontinent>
      <Zemlja>Nemacka</Zemlja>
      <Medalje>
        <Mesto>
          <Lokacija stadion="Stadion2" brMesta="32000">
            <Region>Region2</Region>
            <Grad>Grad2</Grad>
          </Lokacija>
        </Mesto>
        <Medalja>Bronza</Medalja>
        <Godina>2020</Godina>
      </Medalje>
    </Tim2>

    <Termin tvPrenos="false" kanal="3">
      <Datum>2019-05-05</Datum>
      <Cas>12:35:00</Cas>
    </Termin>
    
  </Utakmica>
</RasporedTakmicenja>
